App As appinfo:
    BackEnabled: =false
    OnStart: |
        =// Initialize all collections and variables
        
        // Main phrases collection with all 29 prompting options
        ClearCollect(
            colPhrases,
            // OPTIMAL ANSWERS (25 points each = 100 total)
            {ID: 1, Label: "Describe what you want to do: schedule meetings with availability polling", Weight: 25, Category: "goal", Type: "relevant", Optimal: true},
            {ID: 2, Label: "State your Outlook version and platform (desktop, web, mobile)", Weight: 25, Category: "environment", Type: "relevant", Optimal: true},
            {ID: 3, Label: "Mention your account type (Microsoft 365, Exchange, personal)", Weight: 25, Category: "context", Type: "relevant", Optimal: true},
            {ID: 4, Label: "Ask how to find or enable this scheduling feature", Weight: 25, Category: "plan", Type: "relevant", Optimal: true},
            // GOOD ANSWERS (15-20 points)
            {ID: 5, Label: "Ask if the feature requires admin permissions or a specific license", Weight: 20, Category: "permissions", Type: "relevant", Optimal: false},
            {ID: 6, Label: "Ask what the feature is officially called in Outlook", Weight: 18, Category: "goal", Type: "relevant", Optimal: false},
            {ID: 7, Label: "Ask if it's available in your region or being rolled out", Weight: 18, Category: "context", Type: "relevant", Optimal: false},
            {ID: 8, Label: "Mention where you've already looked (ribbon, settings, add-ins)", Weight: 15, Category: "troubleshooting", Type: "relevant", Optimal: false},
            {ID: 9, Label: "Ask if it's a built-in feature or an add-in to install", Weight: 17, Category: "context", Type: "relevant", Optimal: false},
            {ID: 10, Label: "Ask for a link to Microsoft's official instructions", Weight: 15, Category: "plan", Type: "relevant", Optimal: false},
            // DECENT ANSWERS (8-12 points)
            {ID: 11, Label: "Mention you've searched the ribbon and calendar settings", Weight: 12, Category: "troubleshooting", Type: "helpful", Optimal: false},
            {ID: 12, Label: "Ask if your IT department needs to enable it", Weight: 12, Category: "permissions", Type: "helpful", Optimal: false},
            {ID: 13, Label: "Ask for a brief, focused answer", Weight: 10, Category: "style", Type: "helpful", Optimal: false},
            {ID: 14, Label: "Request step-by-step bullet points", Weight: 10, Category: "style", Type: "helpful", Optimal: false},
            {ID: 15, Label: "Ask the AI to clarify anything it needs first", Weight: 10, Category: "clarifying", Type: "clarifying", Optimal: false},
            {ID: 16, Label: "Ask about alternative ways to poll for meeting times", Weight: 8, Category: "plan", Type: "helpful", Optimal: false},
            {ID: 17, Label: "Ask if the feature has a different name in older versions", Weight: 8, Category: "context", Type: "helpful", Optimal: false},
            {ID: 18, Label: "Ask for keyboard shortcuts to access it faster", Weight: 8, Category: "style", Type: "helpful", Optimal: false},
            // WEAK ANSWERS (2-5 points)
            {ID: 19, Label: "Explain exactly what your colleague said about it", Weight: 3, Category: "context", Type: "weak", Optimal: false},
            {ID: 20, Label: "Ask what version your colleague is using", Weight: 3, Category: "context", Type: "weak", Optimal: false},
            {ID: 21, Label: "Keep the tone casual and friendly", Weight: 5, Category: "style", Type: "weak", Optimal: false},
            {ID: 22, Label: "Mention you're frustrated you can't find it", Weight: 4, Category: "style", Type: "weak", Optimal: false},
            {ID: 23, Label: "Ask for screenshots showing where to click", Weight: 5, Category: "plan", Type: "weak", Optimal: false},
            {ID: 24, Label: "Say you've been searching for a long time", Weight: 5, Category: "context", Type: "weak", Optimal: false},
            {ID: 25, Label: "Ask whether Scheduler is new or old", Weight: 4, Category: "context", Type: "weak", Optimal: false},
            {ID: 26, Label: "Thank the AI before it responds", Weight: 3, Category: "style", Type: "weak", Optimal: false},
            {ID: 27, Label: "Try restarting Outlook before asking", Weight: 2, Category: "troubleshooting", Type: "weak", Optimal: false},
            {ID: 28, Label: "Ask if updating Outlook might help", Weight: 2, Category: "troubleshooting", Type: "weak", Optimal: false},
            {ID: 29, Label: "Ask if the feature works without internet", Weight: 4, Category: "clarifying", Type: "weak", Optimal: false}
        );
        
        // Shuffle phrases for random order
        ClearCollect(colShuffledPhrases, Shuffle(colPhrases));
        
        // Clear selected phrases
        Clear(colSelectedPhrases);
        
        // Hint categories
        ClearCollect(
            colHintCategories,
            {Name: "Goal", Description: "Define what you're looking for and your objective"},
            {Name: "Environment", Description: "Specify your Outlook version and platform"},
            {Name: "Context", Description: "Mention your account type and what you've tried"},
            {Name: "Plan", Description: "Request step-by-step instructions to find the feature"}
        );
        
        // Initialize game state variables
        Set(varGameStarted, false);
        Set(varStartTime, Now());
        Set(varElapsedSeconds, 0);
        Set(varShowResults, false);
        Set(varShowHint, false);
        Set(varTotalScore, 0);
        Set(varOptimalCount, 0);
        Set(varTimeBonus, 0);
        Set(varMaxPossible, 120);
        Set(varPercentage, 0);
        Set(varCoachMessage, "");
        Set(varBaseScore, 0);
        
    Theme: =PowerAppsTheme

    Host As hostControl.HostControl:
        OnCanGoBack: =false
        OnGoBack: =false
